version: '3.3'

services:  
  aplikasi:
    image: 10.63.8.69/fzainal0707/pelatihan
    ports:
      - "30003:80"
    networks:
      - frontend      
networks:
  frontend:
      


    # ports:
    #   - target: 80
    #     published: 30003
    #     mode: none