<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Report_model extends CI_Model {

    public function select_project_charter()
    {
        $query = $this->db->query("select * from T_PROJECT_CHARTER  ");
        return $query->result();
    }


    public function report_detail($bisnis)
    {
        $query = $this->db->query("select A.NASABAH_TIPE,A.ID_NASABAH,A.NAMA,B.CABANG_ULAMM,B.UNIT_ULAMM,B.REGIONAL_MEKAAR,B.AREA_MEKAAR,B.CABANG_MEKAAR,dbo.DESKRIPSI_PELATIHAN_TYPE(B.ID_TIPE) TIPE_PELATIHAN_DESKRIPSI,B.NO_PROPOSAL,B.TITLE,B.TANGGAL_MULAI,C.TANGGAL_REALISASI,B.BUDGET,dbo.DESKRIPSI_GRADING(ID_GRADING) as GRADING,dbo.GRADING_KELAS_WARNA(B.ID_GRADING) as KELAS_WARNA
        from T_KEHADIRAN A 
        INNER JOIN T_PELATIHAN B ON A.ID_PELATIHAN=B.ID
        INNER JOIN T_PELATIHAN_LPJ C ON A.ID_PELATIHAN=C.ID_PELATIHAN
        where ID_BISNIS=$bisnis
        ");
        return $query->result();
    }

    public function report_rekap_ulamm()
    {
        $query = $this->db->query("
        SELECT A.KODE_CABANG,A.DESKRIPSI,B.TUNU_PELATIHAN,B.TUNU_PESERTA,C.TUNCA_PELATIHAN,C.TUNCA_PESERTA,D.SEKTORAL_PELATIHAN,D.SEKTORAL_PESERTA,E.TERITORIAL_PELATIHAN,E.TERITORIAL_PESERTA,F.PAMERAN_PELATIHAN,F.PAMERAN_PESERTA,G.AKBAR_PELATIHAN,G.AKBAR_PESERTA,H.AKBAR_W_PELATIHAN,H.AKBAR_W_PESERTA,I.AKBAR_N_PELATIHAN,I.AKBAR_N_PESERTA,K.REALISASI_BERJALAN_PELATIHAN,J.REALISASI_AKUMULASI_PELATIHAN,K.REALISASI_BERJALAN_PESERTA,J.REALISASI_AKUMULASI_PESERTA FROM MS_CABANG_ULAMM A 
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) TUNU_PELATIHAN,COUNT(T_KEHADIRAN.ID) TUNU_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=1			 and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) B ON A.KODE_CABANG=B.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) TUNCA_PELATIHAN,COUNT(T_KEHADIRAN.ID) TUNCA_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=2			 and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) C ON A.KODE_CABANG=C.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) SEKTORAL_PELATIHAN,COUNT(T_KEHADIRAN.ID) SEKTORAL_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=3	 and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) D ON A.KODE_CABANG=D.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) TERITORIAL_PELATIHAN,COUNT(T_KEHADIRAN.ID) TERITORIAL_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=4 and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) E ON A.KODE_CABANG=E.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) PAMERAN_PELATIHAN,COUNT(T_KEHADIRAN.ID) PAMERAN_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=6		 and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) F ON A.KODE_CABANG=F.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) AKBAR_PELATIHAN,COUNT(T_KEHADIRAN.ID) AKBAR_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=5			 and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) G ON A.KODE_CABANG=G.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) AKBAR_W_PELATIHAN,COUNT(T_KEHADIRAN.ID) AKBAR_W_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=5		 and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) H ON A.KODE_CABANG=H.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) AKBAR_N_PELATIHAN,COUNT(T_KEHADIRAN.ID) AKBAR_N_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=5		 and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) I ON A.KODE_CABANG=I.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) REALISASI_AKUMULASI_PELATIHAN,COUNT(T_KEHADIRAN.ID) REALISASI_AKUMULASI_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE in (1,2,3,4,5,6)		and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) J ON A.KODE_CABANG=J.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) REALISASI_BERJALAN_PELATIHAN,COUNT(T_KEHADIRAN.ID) REALISASI_BERJALAN_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE in (1,2,3,4,5,6) and T_PELATIHAN.TANGGAL_MULAI=GETDATE()	and T_PELATIHAN.ID_BISNIS=1 GROUP BY T_PELATIHAN.CABANG_ULAMM) K ON A.KODE_CABANG=K.CABANG_ULAMM        ");
        return $query->result();
    }      

    public function report_rekap_mekaar()
    {
        $query = $this->db->query("
        SELECT A.KODE_CABANG,A.DESKRIPSI,B.PPNM_PELATIHAN,B.PPNM_PESERTA,C.TUNM_PELATIHAN,C.TUNM_PESERTA,D.SEKTORAL_PELATIHAN,D.SEKTORAL_PESERTA,E.TERITORIAL_PELATIHAN,E.TERITORIAL_PESERTA,F.SINERGI_PELATIHAN,F.SINERGI_PESERTA,H.REALISASI_BERJALAN_PELATIHAN,G.REALISASI_AKUMULASI_PELATIHAN,H.REALISASI_BERJALAN_PESERTA,G.REALISASI_AKUMULASI_PESERTA FROM MS_CABANG_ULAMM A 
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) PPNM_PELATIHAN,COUNT(T_KEHADIRAN.ID) PPNM_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=8			  and T_PELATIHAN.ID_BISNIS=2 GROUP BY T_PELATIHAN.CABANG_ULAMM) B ON A.KODE_CABANG=B.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) TUNM_PELATIHAN,COUNT(T_KEHADIRAN.ID) TUNM_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=9			  and T_PELATIHAN.ID_BISNIS=2 GROUP BY T_PELATIHAN.CABANG_ULAMM) C ON A.KODE_CABANG=C.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) SEKTORAL_PELATIHAN,COUNT(T_KEHADIRAN.ID) SEKTORAL_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=11	  and T_PELATIHAN.ID_BISNIS=2 GROUP BY T_PELATIHAN.CABANG_ULAMM) D ON A.KODE_CABANG=D.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) TERITORIAL_PELATIHAN,COUNT(T_KEHADIRAN.ID) TERITORIAL_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=10 and T_PELATIHAN.ID_BISNIS=2 GROUP BY T_PELATIHAN.CABANG_ULAMM) E ON A.KODE_CABANG=E.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) SINERGI_PELATIHAN,COUNT(T_KEHADIRAN.ID) SINERGI_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE=12		  and T_PELATIHAN.ID_BISNIS=2 GROUP BY T_PELATIHAN.CABANG_ULAMM) F ON A.KODE_CABANG=F.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) REALISASI_AKUMULASI_PELATIHAN,COUNT(T_KEHADIRAN.ID) REALISASI_AKUMULASI_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE in (8,9,10,11,12)		and T_PELATIHAN.ID_BISNIS=2 GROUP BY T_PELATIHAN.CABANG_ULAMM) G ON A.KODE_CABANG=G.CABANG_ULAMM
        LEFT JOIN (SELECT COUNT(T_PELATIHAN.ID) REALISASI_BERJALAN_PELATIHAN,COUNT(T_KEHADIRAN.ID) REALISASI_BERJALAN_PESERTA,T_PELATIHAN.CABANG_ULAMM FROM T_PELATIHAN LEFT JOIN T_KEHADIRAN ON T_PELATIHAN.ID=T_KEHADIRAN.ID_PELATIHAN WHERE T_PELATIHAN.ID_TIPE in (8,9,10,11,12) and T_PELATIHAN.TANGGAL_MULAI=GETDATE()	and T_PELATIHAN.ID_BISNIS=2 GROUP BY T_PELATIHAN.CABANG_ULAMM) H ON A.KODE_CABANG=H.CABANG_ULAMM
        ");
        return $query->result();
    }    
    


}